# Generated by Django 3.2.9 on 2021-12-01 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project Entry', 'verbose_name_plural': 'Project Entries'},
        ),
        migrations.AddField(
            model_name='projectentry',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_entries', to='auth.user'),
            preserve_default=False,
        ),
    ]
