# Generated by Django 3.2.9 on 2021-12-01 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20211201_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectentry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
