version: '3'

services:
  server:
    build: .
    container_name: interesting-projects-api
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: interesting_projects/.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"